Allowing gazebo_world_file arg to be passed in
Robotic-Decision-Making-Lab/blue pull request #148
Opened 2024-01-11 06:15 UTC by timmarkhuff

# Checklist

- [ ] I have performed a thorough review of my code
- [ ] I have sufficiently commented my code
- [ ] The implementation follows the project style conventions
- [ ] All project unit tests are passing
- [ ] If relevant, documentation has been provided or updated to discuss the changes made
- [ ] System integration tests were performed successfully

## Changes Made

Please provide a description of all changes made in this PR and why the changes
are needed.

## Associated Issues

Please provide a list of all open issues that this PR will close or contribute
toward closing.

- Fixes # (issue)

## Testing

Please provide a clear and concise description of the testing performed.

2024-01-11 20:48 UTC, evan-palmer requested changes
Looks good! Would you be willing to update the other launch files as well to ensure consistency across the files?

2024-01-12 04:57 UTC, timmarkhuff commented
> Looks good! Thank you for adding this. Would you be willing to update the other launch files as well to ensure consistency across the files?

This is done.

2024-01-12 07:18 UTC, evan-palmer submitted a review, later dismissed

2024-01-13 22:57 UTC, evan-palmer approved these changes

2024-01-13 22:57 UTC, merged

2024-01-13 23:05 UTC, evan-palmer commented
Thanks for submitting this @timmarkhuff I will get it backported to Iron and Humble